# -*- coding: utf-8 -*-
"""climate_data_into_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EsCX-rY_QhyqOidKPchN3pfEtNvbz-z4
"""

/content/climate_data_brazil_raw.csv
/content/climate_data_ghana_raw.csv
/content/climate_data_indonesia_raw.csv
/content/climate_data_ivory_coast_raw.csv
/content/climate_data_negeria_raw.csv

"""# Task
Process the climate data for Brazil, Ghana, Indonesia, Ivory Coast, and Nigeria. For each country, calculate the yearly average, minimum, and maximum temperatures, and minimum, maximum, average, and total rainfall. Save these yearly statistics into separate CSV files named `yearly_climate_data_<country_name>.csv`, then confirm that all files are ready for upload to the SQL database.

## Process Climate Data per Country

### Subtask:
Iterate through the `climate_dataframes` dictionary, which contains cleaned climate data for Brazil, Ghana, Indonesia, Ivory Coast, and Nigeria. For each country's DataFrame, convert the 'time' column to datetime objects and extract the year.

**Reasoning**:
Iterate through the `climate_dataframes` dictionary, convert the 'time' column to datetime objects, and extract the year into a new 'year' column for each country's DataFrame.
"""

for country, df_country in climate_dataframes.items():
    df_country['time'] = pd.to_datetime(df_country['time'])
    df_country['year'] = df_country['time'].dt.year
    climate_dataframes[country] = df_country

print("Climate dataframes processed with 'time' column converted to datetime and 'year' column added.")
print(climate_dataframes['brazil'].head())

"""## Calculate Yearly Statistics

### Subtask:
For each country's DataFrame, group the data by year and calculate the following statistics: average temperature, minimum temperature, maximum temperature, minimum rainfall, maximum rainfall, average rainfall, and total rainfall.

**Reasoning**:
To calculate the yearly statistics for each country, I will iterate through the `climate_dataframes` dictionary, group each DataFrame by 'year', and then apply aggregation functions for temperature (mean, min, max) and rainfall (mean, min, max, sum). The results will be stored in a new dictionary.
"""

yearly_climate_stats = {}

for country, df_country in climate_dataframes.items():
    # Group by year and calculate statistics
    yearly_stats = df_country.groupby('year').agg(
        yearly_avg_temperature=('temperature', 'mean'),
        yearly_min_temperature=('temperature', 'min'),
        yearly_max_temperature=('temperature', 'max'),
        yearly_min_rainfall=('rainfall', 'min'),
        yearly_max_rainfall=('rainfall', 'max'),
        yearly_avg_rainfall=('rainfall', 'mean'),
        yearly_total_rainfall=('rainfall', 'sum')
    ).reset_index()

    yearly_climate_stats[country] = yearly_stats

print("Yearly climate statistics calculated for all countries.")
# Display the head of one of the processed dataframes to confirm
print(yearly_climate_stats['brazil'].head())

"""**Reasoning**:
Now that the yearly climate statistics have been calculated and stored in the `yearly_climate_stats` dictionary, the next step is to save each country's yearly statistics DataFrame into a separate CSV file as requested by the subtask. The file names should follow the pattern `yearly_climate_data_<country_name>.csv`.


"""

import os

output_directory = "/content/"

# Create the directory if it doesn't exist
if not os.path.exists(output_directory):
    os.makedirs(output_directory)

for country, df_stats in yearly_climate_stats.items():
    output_filename = f"yearly_climate_data_{country}.csv"
    output_filepath = os.path.join(output_directory, output_filename)
    df_stats.to_csv(output_filepath, index=False)
    print(f"Saved {output_filename}")

print("All yearly climate data files have been saved to CSV.")

"""## Final Task

### Subtask:
Confirm that the yearly climate data for all countries has been processed and saved into individual CSV files, ready for upload to the SQL database.

## Summary:

### Q&A
Yes, the yearly climate data for all specified countries (Brazil, Ghana, Indonesia, Ivory Coast, and Nigeria) has been successfully processed and saved into individual CSV files, ready for upload to the SQL database.

### Data Analysis Key Findings
*   The 'time' column in the climate data for Brazil, Ghana, Indonesia, Ivory Coast, and Nigeria was successfully converted to datetime objects, and a new 'year' column was extracted for each country's DataFrame.
*   For each country, comprehensive yearly climate statistics were calculated, including:
    *   Yearly average, minimum, and maximum temperatures.
    *   Yearly minimum, maximum, average, and total rainfall.
*   These calculated yearly statistics were saved into separate CSV files for each country, specifically named `yearly_climate_data_brazil.csv`, `yearly_climate_data_ghana.csv`, `yearly_climate_data_indonesia.csv`, `yearly_climate_data_ivory_coast.csv`, and `yearly_climate_data_negeria.csv`.

### Insights or Next Steps
*   The generated CSV files are now in the correct format and location, making them ready for bulk upload to a SQL database.
*   The aggregated yearly data can be used for further long-term climate trend analysis or comparative studies across the different countries.
"""